#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKhachsan")]
	public partial class DataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDICHVU(DICHVU instance);
    partial void UpdateDICHVU(DICHVU instance);
    partial void DeleteDICHVU(DICHVU instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertPHONG(PHONG instance);
    partial void UpdatePHONG(PHONG instance);
    partial void DeletePHONG(PHONG instance);
    #endregion
		
		public DataContextDataContext() : 
				base(global::QLKS.Properties.Settings.Default.QLKhachsanConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DICHVU> DICHVUs
		{
			get
			{
				return this.GetTable<DICHVU>();
			}
		}
		
		public System.Data.Linq.Table<DICHVUSUDUNG> DICHVUSUDUNGs
		{
			get
			{
				return this.GetTable<DICHVUSUDUNG>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<PHONG> PHONGs
		{
			get
			{
				return this.GetTable<PHONG>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Xoa_Phong")]
		public int Xoa_Phong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string mp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Xoa_Dichvu")]
		public int Xoa_Dichvu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string mdv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mdv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Update_Khachhang")]
		public int Update_Khachhang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string socmnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string mp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> nd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> nt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), socmnd, hoten, diachi, sdt, mp, nd, nt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Xoa_Khachhang")]
		public int Xoa_Khachhang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string socmnd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), socmnd);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Them_Dichvu")]
		public int Them_Dichvu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string mdv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tdv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gdv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mdv, tdv, gdv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Update_Dichvu")]
		public int Update_Dichvu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string mdv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tdv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gdv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mdv, tdv, gdv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_Dichvusudung")]
		public ISingleResult<Select_DichvusudungResult> Select_Dichvusudung()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Select_DichvusudungResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UPDATE_Dichvusudung")]
		public int UPDATE_Dichvusudung()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Them_DVSD")]
		public int Them_DVSD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string socmnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string madv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), socmnd, madv, soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Xoa_DVSD")]
		public int Xoa_DVSD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string socmnd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), socmnd);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Update_DVSD")]
		public int Update_DVSD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string socmnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string madv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> thanhtoan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), socmnd, madv, soluong, thanhtoan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_ThanhtoanDVSD")]
		public ISingleResult<Select_ThanhtoanDVSDResult> Select_ThanhtoanDVSD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cmnd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cmnd);
			return ((ISingleResult<Select_ThanhtoanDVSDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Them_Khachhang")]
		public int Them_Khachhang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string socmnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string mp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> nd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> nt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), socmnd, hoten, diachi, sdt, mp, nd, nt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Them_Phong")]
		public int Them_Phong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string mp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mp, tt, gp, lp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Update_Phong")]
		public int Update_Phong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string mp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mp, tt, gp, lp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Update_Thanhtoan")]
		public int Update_Thanhtoan()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_Nhanvien")]
		public ISingleResult<Select_NhanvienResult> Select_Nhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tentk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tentk);
			return ((ISingleResult<Select_NhanvienResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICHVU")]
	public partial class DICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Madv;
		
		private string _Tendv;
		
		private string _Giadv;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMadvChanging(string value);
    partial void OnMadvChanged();
    partial void OnTendvChanging(string value);
    partial void OnTendvChanged();
    partial void OnGiadvChanging(string value);
    partial void OnGiadvChanged();
    #endregion
		
		public DICHVU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madv", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Madv
		{
			get
			{
				return this._Madv;
			}
			set
			{
				if ((this._Madv != value))
				{
					this.OnMadvChanging(value);
					this.SendPropertyChanging();
					this._Madv = value;
					this.SendPropertyChanged("Madv");
					this.OnMadvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tendv", DbType="NVarChar(50)")]
		public string Tendv
		{
			get
			{
				return this._Tendv;
			}
			set
			{
				if ((this._Tendv != value))
				{
					this.OnTendvChanging(value);
					this.SendPropertyChanging();
					this._Tendv = value;
					this.SendPropertyChanged("Tendv");
					this.OnTendvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giadv", DbType="NVarChar(50)")]
		public string Giadv
		{
			get
			{
				return this._Giadv;
			}
			set
			{
				if ((this._Giadv != value))
				{
					this.OnGiadvChanging(value);
					this.SendPropertyChanging();
					this._Giadv = value;
					this.SendPropertyChanged("Giadv");
					this.OnGiadvChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICHVUSUDUNG")]
	public partial class DICHVUSUDUNG
	{
		
		private string _Socmnd;
		
		private string _Madv;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<double> _Thanhtoan;
		
		public DICHVUSUDUNG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Socmnd", DbType="NVarChar(50)")]
		public string Socmnd
		{
			get
			{
				return this._Socmnd;
			}
			set
			{
				if ((this._Socmnd != value))
				{
					this._Socmnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madv", DbType="NChar(10)")]
		public string Madv
		{
			get
			{
				return this._Madv;
			}
			set
			{
				if ((this._Madv != value))
				{
					this._Madv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this._Soluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanhtoan", DbType="Float")]
		public System.Nullable<double> Thanhtoan
		{
			get
			{
				return this._Thanhtoan;
			}
			set
			{
				if ((this._Thanhtoan != value))
				{
					this._Thanhtoan = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Socmnd;
		
		private string _Hoten;
		
		private string _Diachi;
		
		private string _Sdt;
		
		private string _MaPhong;
		
		private string _Ngayden;
		
		private string _Ngaytra;
		
		private EntityRef<PHONG> _PHONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSocmndChanging(string value);
    partial void OnSocmndChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnNgaydenChanging(string value);
    partial void OnNgaydenChanged();
    partial void OnNgaytraChanging(string value);
    partial void OnNgaytraChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._PHONG = default(EntityRef<PHONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Socmnd", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Socmnd
		{
			get
			{
				return this._Socmnd;
			}
			set
			{
				if ((this._Socmnd != value))
				{
					this.OnSocmndChanging(value);
					this.SendPropertyChanging();
					this._Socmnd = value;
					this.SendPropertyChanged("Socmnd");
					this.OnSocmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(50)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NChar(10)")]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._PHONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayden", DbType="NVarChar(50)")]
		public string Ngayden
		{
			get
			{
				return this._Ngayden;
			}
			set
			{
				if ((this._Ngayden != value))
				{
					this.OnNgaydenChanging(value);
					this.SendPropertyChanging();
					this._Ngayden = value;
					this.SendPropertyChanged("Ngayden");
					this.OnNgaydenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaytra", DbType="NVarChar(50)")]
		public string Ngaytra
		{
			get
			{
				return this._Ngaytra;
			}
			set
			{
				if ((this._Ngaytra != value))
				{
					this.OnNgaytraChanging(value);
					this.SendPropertyChanging();
					this._Ngaytra = value;
					this.SendPropertyChanged("Ngaytra");
					this.OnNgaytraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_KHACHHANG", Storage="_PHONG", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public PHONG PHONG
		{
			get
			{
				return this._PHONG.Entity;
			}
			set
			{
				PHONG previousValue = this._PHONG.Entity;
				if (((previousValue != value) 
							|| (this._PHONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONG.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._PHONG.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(string);
					}
					this.SendPropertyChanged("PHONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONG")]
	public partial class PHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhong;
		
		private string _Tinhtrang;
		
		private string _Giaphong;
		
		private string _Loaiphong;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnTinhtrangChanging(string value);
    partial void OnTinhtrangChanged();
    partial void OnGiaphongChanging(string value);
    partial void OnGiaphongChanged();
    partial void OnLoaiphongChanging(string value);
    partial void OnLoaiphongChanged();
    #endregion
		
		public PHONG()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang", DbType="NVarChar(50)")]
		public string Tinhtrang
		{
			get
			{
				return this._Tinhtrang;
			}
			set
			{
				if ((this._Tinhtrang != value))
				{
					this.OnTinhtrangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang = value;
					this.SendPropertyChanged("Tinhtrang");
					this.OnTinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giaphong", DbType="NVarChar(50)")]
		public string Giaphong
		{
			get
			{
				return this._Giaphong;
			}
			set
			{
				if ((this._Giaphong != value))
				{
					this.OnGiaphongChanging(value);
					this.SendPropertyChanging();
					this._Giaphong = value;
					this.SendPropertyChanged("Giaphong");
					this.OnGiaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loaiphong", DbType="NVarChar(50)")]
		public string Loaiphong
		{
			get
			{
				return this._Loaiphong;
			}
			set
			{
				if ((this._Loaiphong != value))
				{
					this.OnLoaiphongChanging(value);
					this.SendPropertyChanging();
					this._Loaiphong = value;
					this.SendPropertyChanged("Loaiphong");
					this.OnLoaiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = null;
		}
	}
	
	public partial class Select_DichvusudungResult
	{
		
		private string _Hoten;
		
		private string _Socmnd;
		
		private string _Madv;
		
		private string _Tendv;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<double> _Thanhtoan;
		
		public Select_DichvusudungResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this._Hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Socmnd", DbType="NVarChar(50)")]
		public string Socmnd
		{
			get
			{
				return this._Socmnd;
			}
			set
			{
				if ((this._Socmnd != value))
				{
					this._Socmnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madv", DbType="NChar(10)")]
		public string Madv
		{
			get
			{
				return this._Madv;
			}
			set
			{
				if ((this._Madv != value))
				{
					this._Madv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tendv", DbType="NVarChar(50)")]
		public string Tendv
		{
			get
			{
				return this._Tendv;
			}
			set
			{
				if ((this._Tendv != value))
				{
					this._Tendv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this._Soluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanhtoan", DbType="Float")]
		public System.Nullable<double> Thanhtoan
		{
			get
			{
				return this._Thanhtoan;
			}
			set
			{
				if ((this._Thanhtoan != value))
				{
					this._Thanhtoan = value;
				}
			}
		}
	}
	
	public partial class Select_ThanhtoanDVSDResult
	{
		
		private string _tendv;
		
		private System.Nullable<double> _Giadv;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<double> _Thanhtoan;
		
		public Select_ThanhtoanDVSDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendv", DbType="NVarChar(50)")]
		public string tendv
		{
			get
			{
				return this._tendv;
			}
			set
			{
				if ((this._tendv != value))
				{
					this._tendv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giadv", DbType="Float")]
		public System.Nullable<double> Giadv
		{
			get
			{
				return this._Giadv;
			}
			set
			{
				if ((this._Giadv != value))
				{
					this._Giadv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this._Soluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanhtoan", DbType="Float")]
		public System.Nullable<double> Thanhtoan
		{
			get
			{
				return this._Thanhtoan;
			}
			set
			{
				if ((this._Thanhtoan != value))
				{
					this._Thanhtoan = value;
				}
			}
		}
	}
	
	public partial class Select_NhanvienResult
	{
		
		private string _Tennv;
		
		public Select_NhanvienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tennv", DbType="NVarChar(50)")]
		public string Tennv
		{
			get
			{
				return this._Tennv;
			}
			set
			{
				if ((this._Tennv != value))
				{
					this._Tennv = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
